=== greenscar/caffeinewebdesign/from_food/java/Tomcat - (code from learning)/School/WEB-INF/users.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : allUsers.dtd
    Created on : April 28, 2003, 1:46 PM
    Author     : jsandlin
    Description:
        Purpose of the document follows.
-->

<!ELEMENT users (user+)>
<!ELEMENT user (userID, password, name, SSN, empNum, secLvl)>
<!ELEMENT name (firstName, lastName)>
<!ELEMENT userID (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT SSN (#PCDATA)>
<!ELEMENT empNum (#PCDATA)>
<!ELEMENT secLvl (#PCDATA)>

=== greenscar/caffeinewebdesign/from_food/java/Tomcat - (code from learning)/xml testing/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE users SYSTEM "users.dtd">
<!--
    Document   : users.xml
    Created on : April 28, 2003, 1:54 PM
    Author     : jsandlin
    Description:
        Purpose of the document follows.
-->
<users>
  <user>
    <userID>sandlinjames</userID>
    <password>6669</password>
    <firstName>James</firstName>
    <lastName>Sandlin</lastName>
    <SSN>436317733</SSN>
    <empNum>135489</empNum>
    <secLvl>1000</secLvl>
  </user>
  <user>
    <userID>TM</userID>
    <password>TM</password>
    <firstName>Tom</firstName>
    <lastName>Matson</lastName>
    <SSN>275567788</SSN>
    <empNum>123456</empNum>
    <secLvl>10</secLvl>
  </user>
  <user>
    <userID></userID>
    <password></password>
    <firstName></firstName>
    <lastName></lastName>
    <SSN></SSN>
    <empNum></empNum>
    <secLvl></secLvl>
  </user>
</users>

=== greenscar/caffeinewebdesign/from_food/java/Tomcat - (code from learning)/learnDOM/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE users SYSTEM "users.dtd">
<!--
    Document   : users.xml
    Created on : April 28, 2003, 1:54 PM
    Author     : jsandlin
    Description:
        Purpose of the document follows.
-->
<users>
  <user>
    <userID>jsandlin</userID>
    <password>6669</password>
    <name>
        <firstName>James</firstName>
        <lastName>Sandlin</lastName>
    </name>
    <SSN>436317733</SSN>
    <empNum>135489</empNum>
    <secLvl>1000</secLvl>
  </user>
  <user>
    <userID>TM</userID>
    <password>TM</password>
    <name>
        <firstName>Tom</firstName>
        <lastName>Matson</lastName>
    </name>
    <SSN>275567788</SSN>
    <empNum>123456</empNum>
    <secLvl>10</secLvl>
  </user>
</users>
